### ISSUE TITLE
python3-passlib does not exist on CentOS 7

### ISSUE THREAD

**Issue by arlake228** [perfsonar/ansible-role-perfsonar-toolkit#2]
See lines https://github.com/perfsonar/ansible-role-perfsonar-toolkit/blob/476b11be965123c360915ea8247a2dee3099d081/defaults/main.yml#L10-L12

python3-passlib does not exist on CentOS in the base repos, epel or perfSONAR repos. More broadly speaking, ansible playbooks should not need to set dependencies like this. If something like this is needed to set the webadmin password, then it should be in the RPM spec file dependencies.

**Comment by tonin** [comment]
I see this package as being part of the CentOS Extras repository, could we enable it?

I think this dependency doesn't belong to our RPM packaging but only to this role because only Ansible is using it.  When using other management options, the admin can rely on already available CLI tools that don't use the Python bindings.

**Comment by mfeit-internet2** [comment]
Agreed.  If only Ansible needs the package, it should enable the repo and install it.  There's no detriment to the installed system.
